services:
  app:
    image: quarkus/library-jvm:latest  # Nome da imagem gerada pelo Quarkus
    container_name: quarkus-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/meubanco
      - QUARKUS_DATASOURCE_USERNAME=meuusuario
      - QUARKUS_DATASOURCE_PASSWORD=minhasenha
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=update

    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: minhasenha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: